export const Profile = Object.freeze(
    {
    "id":2,
    "email":"admin1@hotmail.com",
    "username":"admin1",
    "password":"$2a$10$SfmFrj7S.b7rEZ./BQMvyerCirgPHVgs5dPhlwgNQxf7dMUE.ZNOG",
    "roles":
        [
            {
                "id":2,
                "name":"ROLE_ADMIN"
            },
            {
                "id":1,
                "name":"ROLE_USER"
            }
        ]
    }
)